version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: bdd
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: psswd
    volumes:
      - ./bdd/data:/var/lib/postgresql/data
      - ./bdd/scripts:/docker-entrypoint-initdb.d
    networks:
      - tomus
    ports:
      - 5432:5432

  words:
    image: cactuspin/tomus-words
    container_name: tomus-words
    ports:
      - 8081:8080
    networks:
      - tomus

networks:
  tomus:
